import tkinter as tk
window = tk.Tk()
window.title('File integrity checker')
window.configure(bg="gray")
window.iconbitmap(r"C:\Users\sujal\Downloads\down.ico")
window.geometry('600x400')
window.resizable(False,False)
label = tk.Label(window,text="Hello guys\n iam learning tkinter\n from\n wscube",font=("Roboto",16,"bold"),bg="gray",fg="green",underline=0,justify="left",cursor="plus",relief="sunken")
label.place(x=50,y=100)
text = input("input string")
var =tk.StringVar()
var.set(text)
label1 = tk.Label(window,textvariable= var,font=("Times Roman",12,"bold"),bg="yellow",fg="black")
label1.place(x=70,y=250)

window.mainloop()
