from tkinter import *
from tkinter import ttk
win =Tk()
notebook=ttk.Notebook(win)
notebook.pack(pady=10,padx=10,expand=True)
style=ttk.Style() # to give padding between frame
style.configure("TNotebook.Tab",padding=(20,5))
f1=ttk.Frame(notebook,height=500,width=500)
f1.config(relief="groove")
f1.pack(fill="both",expand=True)
label=Label(f1,text="python")
label.place(x=10,y=10)
f2=ttk.Frame(notebook,height=500,width=500)
f2.config(relief="groove")
f2.pack(fill="both",expand=True,padx=(10,50))
label2=Label(f2,text="Java")
label2.place(x=10,y=10)
f3=ttk.Frame(notebook,height=500,width=500)
f3.config(relief="groove")
l3=Label(f3,text="hello python")
l3.place(x=10,y=10)
notebook.add(f3,text="python.py")
notebook.add(f1,text="New",padding=5)
notebook.add(f2,text="open",padding=5)
win.mainloop()
