import tkinter as tk
window = tk.Tk()
window.title("File integrity checker")
window.geometry("400x300")
label = tk.Label(window, text="Domain name")
label.grid(row=0, column=0,padx=10,pady=10)
entry = tk.Entry(window)
entry.grid(row=0, column=1,padx=10,pady=10)
label1= tk.Label(window,text="port number")
label1.grid(row=1,column =0,padx=10,pady=10)
entry1=tk.Entry(window)
entry1.grid(row=1,column=1,padx=10,pady=10)
def show_result():
    name = entry.get()
    port = entry1.get()
    print(name)
    print(port)
button = tk.Button(window, text="Scan", command=show_result)
button.place(relx=0.36,rely=0.3)
window.mainloop()