from tkinter import *
win = Tk()
var = StringVar()
def show():
    email=e1.get()
    print(email)
    pa = e2.get()
    print(pa)
    if email=="sujalkc324@gmail.com" and pa=="12345":
        l3.config(text="Login Successful")
    else:
        l3.config(text="login failed")

win.title("Login Page")
win.geometry("500x520")
win.resizable(False,False)
win.config(bg="gray")
win.iconbitmap(r"C:\Users\sujal\Downloads\login.png")
l1=Label(win,text="Email",bg="gray",font=("Times New Roman",20,"bold"))
l1.place(x=80,y=50)
e1=Entry(win,bg="gray",font=14)
e1.place(x=170,y=50,height=40,width=250,)
l2=Label(win,text="Password",bg="gray",font=("Times New Roman",20,"bold"))
l2.place(x=40,y=150)
e2=Entry(win,bg="gray",font=14,show="*")
e2.place(x=170,y=150,height=40,width=250,)
button =Button(win,text="Login ",command=show,font=("Times New Roman",20,"bold"),fg="red",bg="gray")
button.place(x=230,y=250,height=40,width=100)
l3=Label(win,text="",font=("Times New Roman",20,"bold"),bg="gray")
l3.place(x=210,y=310)
win.mainloop()